spring:

  application:
    name: Art

  datasource:
    url: jdbc:postgresql://db-relational:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
    
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_KC_ISSUER_URI}
          jwk-set-uri: ${SPRING_KC_JWK_URI}

  cloud:
    azure:
      servicebus:
        connection-string: ${SPRING_SERVICE_BUS_CONNECTION_STRING}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

aws:
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    endpoint: ${AWS_S3_ENDPOINT}
    url-base: ${AWS_S3_URL_BASE}

imgproxy:
  url: ${IMGPROXY_URL}

stripe:
  secret-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  platform-fee-percent: 15
